#include "arduino_secrets.h"
/* 
AUTHOR: Garima
Student ID: 2110994804
TASK: 3.1P
*/


// DHT sensor library - Version: Latest 
#include <DHT.h>
#include <DHT_U.h>
#define DHTPIN 9 
#define DHTTYPE DHT22
DHT dht(DHTPIN,DHTTYPE);

float temp;
float hum;

/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/f9a64532-30ac-4b78-85f8-50539cda09b5 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudTemperatureSensor temperature;
  CloudRelativeHumidity humidity;
  bool led;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  
  //Initializing DHT-22 sensor
  dht.begin();
  
  //Setting builtin led of arduino nano as an output pin
  pinMode(LED_BUILTIN,OUTPUT);
  
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  
  Serial.print("Temperature ");
  temp = dht.readTemperature();
  Serial.println(temperature);
  temperature = temp;
  
  
  Serial.print("Humidity ");
  hum = dht.readHumidity();
  Serial.println(humidity );
  humidity = hum;
  
  
  delay(3000);    //taking a delay of 30sec between each senso reading
  
}

/*
  Since LED is READ_WRITE variable, onLEDChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLedChange()  {
  // Add your code here to act upon LED change
  digitalWrite(LED_BUILTIN,led);
}










